#!/usr/bin/env python3
"""
generate_scenario.py — pick a random vulnerable-WordPress test scenario.

Reads ci/vulnerable_catalog.json and builds:
  * ci/run/scenario.env    — env vars consumed by docker-compose / entrypoint.sh
  * ci/run/scenario.json   — machine-readable manifest for the e2e assertions
  * ci/run/sites.generated.yaml — SSH site config the wp_audit CLI audits

Randomness is seeded (`--seed` or `--random`), so a failing scenario can be
reproduced exactly. Run from the repo root.
"""

import argparse
import json
import random
import sys
from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parent.parent
CI = ROOT / "ci"
OUTDIR = CI / "run"
CATALOG = CI / "vulnerable_catalog.json"

DEFAULT_SSH_PORT = 3222
DEFAULT_HTTP_PORT = 8080
SSH_PASSWORD = "wp-audit"
SITE_NAME = "CI Vulnerable WordPress"
UNREACHABLE_NAME = "Unreachable Host"


def load_catalog() -> dict:
    with CATALOG.open(encoding="utf-8") as f:
        data = json.load(f)
    data.pop("_meta", None)
    return data


def pick_version(entries: list[str], rng: random.Random) -> str:
    """A scenario picks one concrete version per expected outcome."""
    return rng.choice(entries)


def main() -> None:
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument("--seed", type=int, default=None, help="explicit RNG seed")
    p.add_argument("--random", action="store_true", help="use a fresh random seed (default)")
    p.add_argument("--no-unreachable", action="store_true",
                   help="do not add the unreachable-host scenario site")
    p.add_argument("--ssh-port", type=int, default=DEFAULT_SSH_PORT,
                   help="host port mapped to the container's SSH (default %d)" % DEFAULT_SSH_PORT)
    p.add_argument("--http-port", type=int, default=DEFAULT_HTTP_PORT,
                   help="host port mapped to the container's HTTP (default %d)" % DEFAULT_HTTP_PORT)
    p.add_argument("--outdir", type=Path, default=OUTDIR)
    args = p.parse_args()

    if not args.random and args.seed is None:
        args.seed = random.SystemRandom().randint(0, 2**31 - 1)
    rng = random.Random(args.seed)

    catalog = load_catalog()

    core_version = rng.choice(sorted(catalog["cores"].keys()))

    # Pick one vulnerable plugin + theme, then one DISTINCT outdated each.
    vuln_plugins = sorted(catalog["plugins"])
    vuln_themes = sorted(catalog["themes"])

    vp = rng.choice(vuln_plugins)
    vt = rng.choice(vuln_themes)

    out_plugins = [s for s in vuln_plugins if s != vp]
    out_themes = [s for s in vuln_themes if s != vt]
    op = rng.choice(out_plugins)
    ot = rng.choice(out_themes)

    plugins = [
        (vp, pick_version(catalog["plugins"][vp]["vulnerable"], rng), "vulnerable"),
        (op, pick_version(catalog["plugins"][op]["outdated"], rng), "outdated"),
    ]
    themes = [
        (vt, pick_version(catalog["themes"][vt]["vulnerable"], rng), "vulnerable"),
        (ot, pick_version(catalog["themes"][ot]["outdated"], rng), "outdated"),
    ]
    rng.shuffle(plugins)
    rng.shuffle(themes)

    outdir = args.outdir.resolve()
    outdir.mkdir(parents=True, exist_ok=True)

    # -- scenario.env -------------------------------------------------------
    env_lines = [
        "# generated by ci/generate_scenario.py (seed=%d)" % args.seed,
        "WP_CORE_VERSION=%s" % core_version,
        "WP_PLUGINS=" + ",".join("%s:%s:%s" % t for t in plugins),
        "WP_THEMES=" + ",".join("%s:%s:%s" % t for t in themes),
        "SSH_PASSWORD=%s" % SSH_PASSWORD,
        "WP_ADMIN_PASSWORD=admin",
        "WP_URL=http://127.0.0.1:%d" % args.http_port,
        "WP_SKIP_PROVISION=0",
    ]
    (outdir / "scenario.env").write_text("\n".join(env_lines) + "\n", encoding="utf-8")

    # -- scenario.json (manifest for e2e assertions) ------------------------
    manifest = {
        "seed": args.seed,
        "core": {"slug": core_version, "expect": catalog["cores"][core_version]["expect"]},
        "plugins": [{"slug": s, "version": v, "expect": tag} for s, v, tag in plugins],
        "themes": [{"slug": s, "version": v, "expect": tag} for s, v, tag in themes],
        "unreachable": not args.no_unreachable,
        "ssh_port": args.ssh_port,
        "http_port": args.http_port,
        "site_name": SITE_NAME,
        "unreachable_site_name": UNREACHABLE_NAME,
    }
    (outdir / "scenario.json").write_text(json.dumps(manifest, indent=2), encoding="utf-8")

    # -- sites.generated.yaml (audit CLI config) -----------------------------
    sites = [
        {
            "name": SITE_NAME,
            "host": "127.0.0.1",
            "username": "root",
            "password": SSH_PASSWORD,
            "url": "http://127.0.0.1:%d" % args.http_port,
            "directory": "/var/www/html",
            "port": args.ssh_port,
        },
    ]
    if not args.no_unreachable:
        sites.append({
            "name": UNREACHABLE_NAME,
            "host": "127.0.0.1",
            "username": "root",
            "password": "unused",
            "url": "https://unreachable.invalid",
            "directory": "/var/www/html",
            "port": 1,  # nothing listens on port 1 -> connection refused
        })
    (outdir / "sites.generated.yaml").write_text(
        yaml.safe_dump({"sites": sites}, sort_keys=False), encoding="utf-8")

    print("scenario written to %s (seed=%d)" % (outdir, args.seed))
    print("  core:  %s (%s)" % (core_version, manifest["core"]["expect"]))
    for s, v, tag in plugins:
        print("  plugin %-18s @ %-6s (%s)" % (s, v, tag))
    for s, v, tag in themes:
        print("  theme  %-18s @ %-6s (%s)" % (s, v, tag))
    print("  unreachable site: %s" % ("yes" if manifest["unreachable"] else "no"))


if __name__ == "__main__":
    try:
        main()
    except KeyboardInterrupt:
        sys.exit(130)